### ISSUE TITLE
无法正常关闭窗口

### ISSUE THREAD

**Issue by whxcode** [gennaro-tedesco/nvim-peekup#25] opened 2022-08-09 14:09 UTC
我在使用过程中发现了一个小问题，打开窗口；使用以下快捷键
let g:peekup_paste_before = '<leader>q'
let g:peekup_paste_after = '<leader>p'
选择了对应了寄存器之后，在光标的前/后插入了文本之后;窗口没能自动关闭，且按 esc 键，也无法关闭。
![image](https://user-images.githubusercontent.com/44012914/183670575-8387500c-6adc-434d-af8b-10d70891bbf9.png)
如图，光标已经聚焦到编辑器内部了。

**Comment by gennaro-tedesco** [comment] 2022-08-09 14:22
Good afternoon and thank you for looking into `nvim-peekup`: I would ask you to edit the text in English character (I suppose you have your keyboard set to something else and did not realise), otherwise I cannot read it :)

**Comment by whxcode** [comment] 2022-08-09 14:34
> Good afternoon and thank you for looking into `nvim-peekup`: I would ask you to edit the text in English characters (I suppose you have your keyboard set to something else and did not realise), otherwise I cannot read it :)

Sorry, my English is not good. Thank you for your answer.

**Comment by gennaro-tedesco** [comment] 2022-08-09 14:40
Trying to use google translate on your text it seems you are seeing problems in closing the window after pressing `ESC`: this happens because the focussed window is no longer the `peekup` window in your example (most likely you moved the cursor elsewhere, on another window of the editor). The `ESC` key-binding only works when the focus in on `peekup`: so  switch the focus/cursor back on the peekup window and it will close :).

**Comment by whxcode** [comment] 2022-08-09 14:45
> Trying to use google translate on your text it seems you are seeing problems in closing the window after pressing `ESC`: this happens because the focussed window is no longer the `peekup` window in your example (most likely you moved the cursor elsewhere, on another window of the editor). The `ESC` key-binding only works when the focus in on `peekup`: so switch the focus/cursor back on the peekup window and it will close :).

Yes, because after pasting, the 'peekup' window has lost focus, but I don't know how to switch the focus to the 'peekup' window.

**Comment by gennaro-tedesco** [comment] 2022-08-09 15:18
> but I don't know how to switch the focus to the 'peekup' window.

you can just cycle through all your open windows with `<C-w>w/W`

**Closed** 2022-08-09 16:34 UTC

**Comment by whxcode** [comment] 2022-08-10 01:02
> > but I don't know how to switch the focus to the 'peekup' window.
> 
> you can just cycle through all your open windows with `<C-w>w/W`

Good evening, I have tried to use the <C-W>w/W keys yesterday; switch windows, but still can't switch back to the peekup window.
I am using nvim v0.8.0-dev version.
thanks for your reply.

**Comment by gennaro-tedesco** [comment] 2022-08-10 07:43
Can you not cycle through windows at all or can you indeed, and the peekup window is never selected? Could you try just clicking on the window with the mouse instead (just to ensure that the focus is there)?

**Comment by whxcode** [comment] 2022-08-10 08:46
> Can you not cycle through windows at all or can you indeed, and the peekup window is never selected? Could you try just clicking on the window with the mouse instead (just to ensure that the focus is there)?

I've tried many ways, but I can't get the focus back inside the peekup .

**Comment by gennaro-tedesco** [comment] 2022-08-10 09:04
In the video below you can see that whenever the focus is indeed on the peekup window, it closes fine. In order to cycle it back and forth I am using the mouse click (for demonstration, but `<C-w>w` would do too)

https://user-images.githubusercontent.com/15387611/183861314-b323e704-7239-4a7a-9c35-01eff8c6a1a7.mov

> I've tried many ways, but I can't get the focus back inside the peekup .

this seems however not to be a problem of the plugin per sé, rather of how your neovim instance cycles through the open windows. Could you try to reproduce the demo I showed on your computer? Namely what happens when you do click back on peekup?

**Comment by whxcode** [comment] 2022-08-10 12:09
> In the video below you can see that whenever the focus is indeed on the peekup window, it closes fine. In order to cycle it back and forth I am using the mouse click (for demonstration, but `<C-w>w` would do too)
> 
>  Screen.Recording.2022-08-10.at.11.01.26.mov 
> > I've tried many ways, but I can't get the focus back inside the peekup .
> 
> this seems however not to be a problem of the plugin per sé, rather of how your neovim instance cycles through the open windows. Could you try to reproduce the demo I showed on your computer? Namely what happens when you do click back on peekup?

Sorry, it took so long to reply to you, I just tested it on my own laptop at home, after pasting the content, I can focus on 'peekup' again through C-w/w, the laptop in the company may be caused by other reasons, I will tomorrow Double check, thanks for your help.

**Comment by whxcode** [comment] 2022-08-10 12:14
> In the video below you can see that whenever the focus is indeed on the peekup window, it closes fine. In order to cycle it back and forth I am using the mouse click (for demonstration, but `<C-w>w` would do too)
> 
>  Screen.Recording.2022-08-10.at.11.01.26.mov 
> > I've tried many ways, but I can't get the focus back inside the peekup .
> 
> this seems however not to be a problem of the plugin per sé, rather of how your neovim instance cycles through the open windows. Could you try to reproduce the demo I showed on your computer? Namely what happens when you do click back on peekup?

gut nacht.
